### ISSUE TITLE
Package doesn't run on aarch64 architecture

### ISSUE THREAD

**Issue by Feakster** [yurikoles-aur/minecraft#1]
I've just tried installing this on Manjaro ARM on a Pinebook Pro, but I'm getting exec format errors. The PKGBUILD says this is for any architecture. Might need to change it to x86_64 or change something.

**Comment by Dam-0** [comment]
This is the .deb version which requires x86_64
The .jar version would would on ARM if you have java installed

**Comment by Feakster** [comment]
So the .deb is the bedrock version? Not the java version?

**Comment by ThePuzzlemaker** [comment]
The .deb is the native x86_64 launcher for Java edition, it's a compiled binary for x86_64 that handles (most) of the Java installation/version stuff with (usually) little problem. There's also the [.jar version of the launcher](https://launcher.mojang.com/download/Minecraft.tar.gz) which is still the same launcher, however, it's just presented in the format of a .jar rather than a compiled binary.

Hope this explanation helps.

**Comment by Feakster** [comment]
Hi,

Yes, this helps. Unfortunately, the .jar version still comes with a bundled launcher that is platform-dependent. I guess I'm out of luck. Embrace, extend, and extinguish is still very much a mantra of Microsoft.
